export const BOOKS = [
  {
    slug: "why-youre-creatively-blocked",
    title: "Why You're Creatively Blocked",
    format: "Paperback",
    image: "/books/creatively-blocked.jpg",
    link: "https://www.lulu.com/shop/wanda-rogers/why-youre-creatively-blocked/paperback/product-kvddgn4.html?page=1&pageSize=4",
    description: "A guide for creatives navigating resistance, rebuilding momentum, and learning how to work with their creativity instead of against it.",
    longDescription: "Creative blocks are not character flaws. They are signals. This book breaks down the most common forms of creative resistance -- perfectionism, overthinking, distraction, burnout -- and gives you a framework for understanding what yours is actually telling you. Through honest writing and practical exercises, you will learn to move through what has been stopping you and build a creative practice that is sustainable, authentic, and yours.",
    cta: "Get Unblocked Now",
    themes: ["Creative resistance", "Self-trust", "Momentum", "Identity"],
  },
  {
    slug: "the-first-to-make-it-this-far",
    title: "The First to Make It This Far",
    format: "Paperback",
    image: "/books/first-to-make-it.jpg",
    link: "https://www.lulu.com/shop/wanda-rogers/the-first-to-make-it-this-far/paperback/product-yvkv7yd.html?page=1&pageSize=4",
    description: "A story about resilience, identity, and making it through what was supposed to break you.",
    longDescription: "What does it cost to become someone no one in your family has ever been? This book is a memoir of first-generation ambition -- the isolation, the imposter syndrome, the grief of outgrowing spaces you once called home, and the quiet pride that comes with building something entirely your own. It is for anyone who has ever felt like they were becoming too much and not enough at the same time.",
    cta: "Read My Story",
    themes: ["First-generation identity", "Ambition", "Belonging", "Resilience"],
  },
]

export const WORKBOOKS = [
  {
    slug: "overthinking-workbook",
    title: "The Overthinking Workbook",
    archetype: "Overthinker",
    tint: "bg-lavenderTint",
    accentText: "text-brandPurple",
    price: "$27",
    href: "#",
    description: "Stop analyzing and start making. A guided process for breaking the loop, moving through paralysis, and building the muscle of decisive action.",
  },
  {
    slug: "perfectionists-permission-slip",
    title: "The Perfectionist's Permission Slip",
    archetype: "Perfectionist",
    tint: "bg-blueTint",
    accentText: "text-brandBlue",
    price: "$27",
    href: "#",
    description: "Let go of the standard that's keeping you stuck. Exercises for building \"good enough\" momentum. Finished beats flawless.",
  },
  {
    slug: "focus-fix",
    title: "The Focus Fix",
    archetype: "Distracted",
    tint: "bg-peachTint",
    accentText: "text-brandOrange",
    price: "$27",
    href: "#",
    description: "For creatives who can't stay in the chair. Practical systems for the distracted maker: boundary-setting, time-blocking, and reclaiming your own creative hours.",
  },
  {
    slug: "idea-graveyard",
    title: "The Idea Graveyard",
    archetype: "Idea Hopper",
    tint: "bg-lavenderTint",
    accentText: "text-brandPurple",
    price: "$27",
    href: "#",
    description: "Finish what you started. A structured excavation of your abandoned projects: finding out which ones still matter and building the commitment to see them through.",
  },
  {
    slug: "burnout-recovery-guide",
    title: "The Burnout Recovery Guide",
    archetype: "Burnout",
    tint: "bg-peachTint",
    accentText: "text-brandOrange",
    price: "$27",
    href: "#",
    description: "Reignite slowly, sustainably. Rest is part of the process, not a detour from it. A step-by-step guide to rebuilding creative energy from the ground up.",
  },
]

export const COMPANION = {
  title: "The Creative Clarity Companion",
  price: "$97",
  originalPrice: "$135",
  href: "#",
  description: "All 5 workbooks plus a complete 12-week guided program, structured by archetype, paced for real life. One price. One process.",
  tags: ["All 5 workbooks included", "12-week guided program", "Archetype-specific path"],
}
